# Generated by Django 5.0.4 on 2024-04-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Tipo_Doc', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
