# Generated by Django 5.0.4 on 2024-05-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idIns', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('idPue', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('idTipoDoc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pssword', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('idDoc', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('fecha_emi', models.DateField()),
                ('fecha_rec', models.DateField()),
                ('pdf_doc', models.FileField(upload_to='documentos/')),
                ('dep_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_des', to='api.departamento')),
                ('dep_rem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_rem', to='api.departamento')),
                ('ins_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_des', to='api.institucion')),
                ('ins_rem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_rem', to='api.institucion')),
                ('usu_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usu_des', to='api.usuario')),
                ('usu_rem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usu_rem', to='api.usuario')),
            ],
        ),
    ]
