# Generated by Django 5.0.4 on 2024-04-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodoc',
            name='id_Tipo_Doc',
        ),
    ]
