# Generated by Django 5.0.4 on 2024-05-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsu',
            new_name='id',
        ),
    ]
