# Generated by Django 5.0.4 on 2024-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departamento_institucion_puesto_usuario_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='id_ins',
            new_name='idIns',
        ),
        migrations.RemoveField(
            model_name='tipodoc',
            name='id',
        ),
        migrations.AddField(
            model_name='tipodoc',
            name='idTipoDoc',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
