# Generated by Django 5.0.4 on 2024-05-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_ins_institucion_idins_remove_tipodoc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='id_dep',
            new_name='idDep',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='id_doc',
            new_name='idDoc',
        ),
        migrations.RenameField(
            model_name='puesto',
            old_name='id_pue',
            new_name='idPue',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usu',
            new_name='idUsu',
        ),
    ]
